title: tiny stories
position: flash fiction from scotland
affiliation: 
email: 
keywords: fiction
google_scholar: 
github_link: 
linkedin: 
avatar: ./assets/img/avatar.png
google_analytics: 
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: Flash fiction from Scotland.
canonical: https://tiny-stories.github.io
remote_theme: yaoyao-liu/minimal-light
